[build]
  publish = "build/"

[[redirects]]
  from = "/compile/*"
  to = "http://cexplore.henny022.de/api/compiler/tmc_agbcc/compile/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200