name: reviewdog
on: pull_request
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && yarn
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
          workdir: frontend
          eslint_flags: src --ext .js,.jsx,.ts,.tsx
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
      - run: cd frontend && yarn && yarn run tsc | reviewdog -f tsc -reporter github-pr-check
