name: reviewdog
on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
      - run: cd frontend && yarn
      - run: pip install -r backend/requirements.txt
      - run: reviewdog -reporter=github-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
